from iCLIP.utils.registry import Registry

BACKBONES = Registry()
ROI_ACTION_FEATURE_EXTRACTORS = Registry()
ROI_ACTION_PREDICTORS = Registry()
TEXT_FEATURE_GENERATOR = Registry()
INTERACTION_AGGREGATION_STRUCTURES = Registry()
VIDEO_FEATURE_GENERATOR = Registry()